### ISSUE TITLE
Potential Infinite Loop for Patch Match Notebook

### ISSUE THREAD

**Issue by cabreraalex** [AlexandreSev/Patch-Match#1]
I'm attempting to run the patch match notebook, but the final execution is taking more than 10 minutes to complete. Is this normal?

Thanks!
Alex

**Comment by AlexandreSev** [comment]
Indeed, there is a bug with the multiprocessing, and there is an issue with the new version of networkx. I'll try to fix this this week-end :)
Thank's for your feedback !
Alex

**Comment by AlexandreSev** [comment]
I wrote a quick fix.
I'll do something cleaner soon.
Tell me if it works :)

**Comment by cabreraalex** [comment]
It works, thank you so much!
